version: '3.8'
services:
  financial-risk-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
      - "5001:5001"
    volumes:
      - ./Data:/app/Data
      - ./Models:/app/Models
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - FLASK_PORT=5001
      - FLASK_HOST=0.0.0.0
      - PYTHONPATH=/app
      - MODEL_PATH=/app/Models/trained_models/
      - DATA_PATH=/app/Data/
      - CONTAINER_ENV=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
