name: financialRisk
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - _openmp_mutex=4.5
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.12.13
  - aiohttp-retry=2.9.1
  - aiosignal=1.3.2
  - alembic=1.16.2
  - altair=5.5.0
  - amqp=5.2.0
  - annotated-types=0.7.0
  - antlr-python-runtime=4.9.3
  - anyio=4.9.0
  - appdirs=1.4.4
  - asttokens=3.0.0
  - async-timeout=5.0.1
  - asyncssh=2.21.0
  - atpublic=6.0.1
  - attrs=25.3.0
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.3
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.4
  - aws-c-http=0.10.2
  - aws-c-io=0.20.1
  - aws-c-mqtt=0.13.1
  - aws-c-s3=0.8.1
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.32.8
  - aws-sdk-cpp=1.11.510
  - bcrypt=4.3.0
  - billiard=4.2.1
  - blinker=1.9.0
  - boto3=1.38.41
  - botocore=1.38.41
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.7.14
  - cachetools=5.5.2
  - cairo=1.18.4
  - celery=5.5.3
  - certifi=2025.7.14
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - click=8.2.1
  - click-didyoumean=0.3.1
  - click-plugins=1.1.1
  - click-repl=0.3.0
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - colorlog=6.9.0
  - comm=0.2.2
  - configobj=5.0.9
  - contourpy=1.3.2
  - cpython=3.10.18
  - cryptography=45.0.4
  - cuda-version=12.9
  - cycler=0.12.1
  - dacite=1.9.2
  - databricks-sdk=0.56.0
  - dataclasses=0.8
  - debugpy=1.8.14
  - decorator=5.2.1
  - deprecated=1.2.18
  - dictdiffer=0.9.0
  - diskcache=5.6.3
  - distro=1.9.0
  - dnspython=2.7.0
  - docker-py=7.1.0
  - double-conversion=3.3.1
  - dpath=2.2.0
  - dulwich=0.23.0
  - dvc=3.60.1
  - dvc-data=3.16.10
  - dvc-http=2.32.0
  - dvc-objects=5.1.1
  - dvc-render=1.0.2
  - dvc-studio-client=0.21.0
  - dvc-task=0.40.2
  - email-validator=2.2.0
  - email_validator=2.2.0
  - entrypoints=0.4
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - fastapi=0.115.13
  - fastapi-cli=0.0.7
  - filelock=3.18.0
  - flask=3.1.1
  - flask-cors=6.0.1
  - flatten-dict=0.4.2
  - flufl.lock=8.2.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.58.4
  - freetype=2.13.3
  - fribidi=1.0.10
  - frozenlist=1.6.0
  - fsspec=2025.5.1
  - funcy=2.0
  - future=1.0.0
  - getopt-win32=0.1
  - gitdb=4.0.12
  - gitpython=3.1.44
  - glib=2.84.2
  - glib-tools=2.84.2
  - google-auth=2.40.3
  - grandalf=0.7
  - graphene=3.4.3
  - graphite2=1.3.14
  - graphql-core=3.2.6
  - graphql-relay=3.2.0
  - graphviz=13.0.1
  - greenlet=3.2.3
  - gst-plugins-base=1.24.11
  - gstreamer=1.24.11
  - gto=1.7.2
  - gts=0.7.6
  - h11=0.16.0
  - h2=4.2.0
  - harfbuzz=11.2.1
  - hpack=4.1.0
  - htmlmin=0.1.12
  - httpcore=1.0.9
  - httptools=0.6.4
  - httpx=0.28.1
  - hydra-core=1.3.2
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - imagehash=4.3.1
  - importlib-metadata=8.7.0
  - importlib_resources=6.5.2
  - iniconfig=2.0.0
  - intel-openmp=2024.2.1
  - ipykernel=6.29.5
  - ipython=8.37.0
  - ipython_pygments_lexers=1.1.1
  - iterative-telemetry=0.0.10
  - itsdangerous=2.2.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - jmespath=1.0.1
  - joblib=1.5.1
  - jsonschema=4.24.0
  - jsonschema-specifications=2025.4.1
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - kiwisolver=1.4.7
  - kombu=5.5.4
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20250127.1
  - libarrow=19.0.1
  - libarrow-acero=19.0.1
  - libarrow-dataset=19.0.1
  - libarrow-substrait=19.0.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang13=20.1.7
  - libcrc32c=1.1.2
  - libcurl=8.14.1
  - libdeflate=1.24
  - libevent=2.1.12
  - libexpat=2.7.0
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgd=2.3.3
  - libgit2=1.9.1
  - libglib=2.84.2
  - libgomp=15.1.0
  - libgoogle-cloud=2.36.0
  - libgoogle-cloud-storage=2.36.0
  - libgrpc=1.71.0
  - libhwloc=2.11.2
  - libiconv=1.18
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libmpdec=4.0.0
  - libogg=1.3.5
  - libparquet=19.0.1
  - libpng=1.6.49
  - libpq=17.5
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libsodium=1.0.20
  - libsqlite=3.50.1
  - libssh2=1.11.1
  - libthrift=0.21.0
  - libtiff=4.7.0
  - libutf8proc=2.10.0
  - libvorbis=1.3.7
  - libwebp-base=1.5.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxcb=1.17.0
  - libxgboost=3.0.2
  - libxml2=2.13.8
  - libxslt=1.1.39
  - libzlib=1.3.1
  - llvmlite=0.43.0
  - lz4-c=1.10.0
  - mako=1.3.10
  - markdown=3.8.2
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib=3.8.0
  - matplotlib-base=3.8.0
  - matplotlib-inline=0.1.7
  - mdurl=0.1.2
  - mkl=2024.2.2
  - mlflow=3.1.0
  - mlflow-skinny=3.1.0
  - mlflow-ui=3.1.0
  - multidict=6.5.0
  - multimethod=1.12
  - munkres=1.1.4
  - narwhals=1.46.0
  - nest-asyncio=1.6.0
  - networkx=3.4
  - numba=0.60.0
  - numpy=1.23.5
  - omegaconf=2.3.0
  - openjpeg=2.5.3
  - openssl=3.5.1
  - opentelemetry-api=1.34.1
  - opentelemetry-sdk=1.34.1
  - opentelemetry-semantic-conventions=0.55b1
  - optuna=4.4.0
  - orc=2.1.2
  - orjson=3.10.18
  - packaging=24.2
  - pandas=2.3.0
  - pango=1.56.3
  - paramiko=3.5.1
  - parso=0.8.4
  - pathlib2=2.3.7.post1
  - pathspec=0.12.1
  - patsy=1.0.1
  - pcre2=10.45
  - phik=0.12.4
  - pickleshare=0.7.5
  - pillow=11.2.1
  - pip=25.1.1
  - pixman=0.46.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.8
  - plotly=6.2.0
  - pluggy=1.6.0
  - ply=3.11
  - prometheus_client=0.22.1
  - prometheus_flask_exporter=0.23.2
  - prompt-toolkit=3.0.51
  - prompt_toolkit=3.0.51
  - propcache=0.3.1
  - protobuf=5.29.3
  - psutil=7.0.0
  - psycopg2=2.9.10
  - psycopg2-binary=2.9.10
  - pthread-stubs=0.4
  - pure_eval=0.2.3
  - py-xgboost=3.0.2
  - pyarrow=19.0.1
  - pyarrow-core=19.0.1
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.2
  - pycparser=2.22
  - pydantic=2.11.7
  - pydantic-core=2.33.2
  - pydeck=0.9.1
  - pydot=4.0.1
  - pygit2=1.18.0
  - pygments=2.19.1
  - pygtrie=2.5.0
  - pynacl=1.5.0
  - pyopenssl=25.1.0
  - pyparsing=3.2.3
  - pyqt=5.15.11
  - pyqt5-sip=12.17.0
  - pyside6=6.9.1
  - pysocks=1.7.1
  - pytest=8.4.1
  - python=3.10.10
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.1.1
  - python-gssapi=1.9.0
  - python-multipart=0.0.20
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytz=2025.2
  - pyu2f=0.1.5
  - pywavelets=1.8.0
  - pywin32=307
  - pywin32-on-windows=0.1.0
  - pyyaml=6.0.2
  - pyzmq=27.0.0
  - qhull=2020.2
  - qt-main=5.15.15
  - qt6-main=6.9.1
  - querystring_parser=1.2.4
  - re2=2024.07.02
  - referencing=0.36.2
  - requests=2.32.4
  - rich=14.0.0
  - rich-toolkit=0.11.3
  - rpds-py=0.26.0
  - rsa=4.9.1
  - ruamel.yaml=0.18.14
  - ruamel.yaml.clib=0.2.8
  - s3transfer=0.13.0
  - scikit-learn=1.7.0
  - scipy=1.13.1
  - scmrepo=3.3.11
  - seaborn-base=0.13.2
  - semver=3.0.4
  - setuptools=80.9.0
  - shellingham=1.5.4
  - shortuuid=1.0.13
  - shtab=1.7.2
  - sip=6.10.0
  - six=1.17.0
  - smmap=5.0.2
  - snappy=1.2.1
  - sniffio=1.3.1
  - sqlalchemy=2.0.41
  - sqlparse=0.5.3
  - sqltrie=0.11.2
  - stack_data=0.6.3
  - starlette=0.46.2
  - statsmodels=0.14.4
  - streamlit=1.47.0
  - tabulate=0.9.0
  - tbb=2021.13.0
  - tenacity=9.1.2
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.2.1
  - tomlkit=0.13.3
  - tornado=6.5.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typeguard=4.4.4
  - typer=0.16.0
  - typer-slim=0.16.0
  - typer-slim-standard=0.16.0
  - typing-extensions=4.14.0
  - typing-inspection=0.4.1
  - typing_extensions=4.14.0
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - unicodedata2=16.0.0
  - urllib3=2.5.0
  - uvicorn=0.34.3
  - uvicorn-standard=0.34.3
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vine=5.1.0
  - visions=0.7.6
  - voluptuous=0.15.2
  - vs2015_runtime=14.44.35208
  - waitress=3.0.2
  - watchdog=6.0.0
  - watchfiles=1.1.0
  - wcwidth=0.2.13
  - websocket-client=1.8.0
  - websockets=15.0.1
  - werkzeug=3.1.3
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - wordcloud=1.9.4
  - wrapt=1.17.2
  - xgboost=3.0.2
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxpm=3.5.17
  - xorg-libxt=1.3.1
  - xz=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - yarl=1.20.1
  - ydata-profiling=4.16.0
  - zc.lockfile=3.0.post1
  - zeromq=4.3.5
  - zipp=3.23.0
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - altgraph==0.17.4
      - bottle==0.13.4
      - clr-loader==0.2.7.post0
      - coverage==7.10.0
      - pefile==2023.2.7
      - proxy-tools==0.1.0
      - pyinstaller==6.14.2
      - pyinstaller-hooks-contrib==2025.7
      - pyqt6==6.9.1
      - pyqt6-qt6==6.9.1
      - pyqt6-sip==13.10.2
      - pyqt6-webengine==6.9.0
      - pyqt6-webengine-qt6==6.9.1
      - pytest-cov==6.2.1
      - pythonnet==3.0.5
      - pywebview==5.4
      - pywin32-ctypes==0.2.3
      - qtpy==2.4.3
